RetailBankManagementSystem/Controllers/ExecutiveController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using RetailBankManagementSystem.Models;
using RetailBankManagementSystem.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RetailBankManagementSystem.Controllers
{
    [Authorize(Roles = "CustomerExecutive")]
    public class ExecutiveController : Controller
    {
        private List<string> states = new List<string> { "FL", "IL", "WI" };
        private List<string> cities = new List<string> { "Miami", "Fort Lauderdale", "Boca Raton", "Chicago", "Naperville", "Springfield", "Madisson", "Milwakee", "Green Bay" };

        private ICustomerExecutiveRepo _repo;

        public ExecutiveController(ICustomerExecutiveRepo repo)
        {
            _repo = repo;
        }

        public IActionResult ViewAccountsIndex(ViewAccountViewModel viewacc)
        {
            long? accountID = ModelState.IsValid ? viewacc.AccountID : null;
            viewacc.Accounts = _repo.ViewAccounts(viewacc.PageIndex ?? 1, accountID);
            return View(viewacc);
        }

        
        public IActionResult DeleteAccount(long ID, String? flag)
        {
            TempData["redirect"] = null;
            if (flag == "true")
            {
                TempData["redirect"] = "true";
            }
            Account account = _repo.GetAccountByAccountID(ID);
            return View(account);
        }

        [HttpPost]
        public IActionResult DeleteAccount(Account account)
        {
            long customerId = account.CustomerID;
            TempData["accountdeletion"] = null;
            if (account == null)
            {
                TempData["accountdeletion"] = "Account doesn't exist";
                return RedirectToAction("ViewAccountsIndex");

            }
            else
            {
                _repo.DeleteAccount(account);               
                String rand = TempData["redirect"] == null ? "" : TempData["redirect"].ToString();
                if (rand.Equals("true"))
                {
                    TempData["redirect"] = null;
                    return RedirectToAction("DeleteCustomer", new { CustomerID = customerId });
                } else
                {
                    TempData["accountdeletion"] = "Account " + account.AccountID + " is deleted successfully";
                    return RedirectToAction("ViewAccountsIndex");
                }
                
            }
        }
        public IActionResult Index(int? pageNumber)
        {
            //return View(_repo.ViewAllCustomers(PageIndex ?? 1));
            var customerList = _repo.ViewAllCustomers();
            int pageSize = 5;
            return View(PagingList<Customer>.CreateAsync(
                customerList.AsQueryable<Customer>(),
                pageNumber ?? 1,
                pageSize));
        }

        public IActionResult Create()
        {
           
            CustomerCreateViewModel cvm = new CustomerCreateViewModel
            {
                States = states,
                Cities = cities
            };
            return View(cvm);
        }
        [HttpPost]
        public IActionResult Create(CustomerCreateViewModel customer)
        {
            
            if (ModelState.IsValid)
            {
                Customer cs = _repo.getCustomerBySsn(Convert.ToInt64(customer.CustomerDetails.SSN));
                if (cs == null)
                {
                    customer.CustomerDetails.Address = customer.AddressLine1 + ", " + customer.AddressLine2;
                    _repo.AddCustomer(customer.CustomerDetails);
                    TempData["customerAddSuccess"] = $"Customer was added successfully! Customer ID: {customer.CustomerDetails.CustomerID}";
                    return RedirectToAction("Index");
                }
                TempData["customerAddFail"] = $"Customer could not be added. SSN is already linked to another customer account";
                return RedirectToAction("Index");
            }
          
            CustomerCreateViewModel cvm = new CustomerCreateViewModel
            {
                States = states,
                Cities = cities
            };
            return View(cvm);
        }
        
        
        public IActionResult viewStatus(int pageNo)
        {
            if(pageNo == 0)
            {
                pageNo = 1;
            }
            CustomerAccViewModel acc = new CustomerAccViewModel();
            acc.customerAccs = _repo.viewStatus().customerAccs;
            return View(PagingList<CustomerAcc>.CreateAsync(acc.customerAccs.AsQueryable<CustomerAcc>(), pageNo, 5));
        }

        public IActionResult SearchCustomer()
        {
            TempData["customer"] = null;
            return View();
        }

        //[HttpPost]
        //public IActionResult SearchCustomer(Customer customer)
        //{
        //    if (customer.CustomerID == 0)
        //        ModelState.Remove("CustomerID");
        //    else
        //        ModelState.Remove("SSN");

        //    List<Customer> cs = new List<Customer>();
        //    TempData["customer"] = null;
        //        if (customer.SSN == 0)
        //        {
        //            cs.Add(_repo.getCustomerByCID(customer.CustomerID));

        //            if (!cs.Contains(null))
        //            {
        //                TempData["customer"] = "we have a value";
        //            }
        //            return View(cs.First());
        //        }
        //        else
        //        {
        //            cs.Add(_repo.getCustomerBySsn(customer.SSN));
        //            if (!cs.Contains(null))
        //            {
        //                TempData["customer"] = "we have a value";
        //            }
        //            return View(cs.First());
        //        }
        //}


        [HttpPost]
        public IActionResult SearchCustomer(CustSearch customer)
        {
            if (customer.CustomerID == 0)
                ModelState.Remove("CustomerID");
            else
                ModelState.Remove("SSN");
            long customerId = customer.CustomerID;
            long ssn = customer.SSN;

            ViewData["SearchParams"] = null;
            if (customerId == 0 && ssn == 0)
            {
                ModelState.Remove("CustomerID");
                ModelState.Remove("SSN");
                ViewData["SearchParams"] = "Please Provide A Value!";
                return View("SearchCustomer");
            }

            List<Customer> cs = new List<Customer>();
            TempData["customer"] = null;
            if (!ModelState.IsValid)
            {
                return View("SearchCustomer");
            }
            if (customer.SSN == 0)
            {
                cs.Add(_repo.getCustomerByCID(customer.CustomerID));

                if (cs.Contains(null))
                {
                    TempData["customer"] = "we have a null value";
                    return View();
                } else
                {

                    return View("viewCustomerDetails", cs.First());
                }                
            }
            else
            {
                cs.Add(_repo.getCustomerBySsn(customer.SSN));
                if (cs.Contains(null))
                {
                    TempData["customer"] = "we have a null value";
                    return View();
                }
                else
                {
                    return View("viewCustomerDetails", cs.First());
                }
            }
        }

        public IActionResult viewCustomerDetails(Customer customer)
        {            
            return View(customer);
        }

        public IActionResult viewAccountDetails(long CustomerID)
        {
            return View(_repo.GetAccountByCustomerID(CustomerID));
        }

        [HttpGet]
        public IActionResult DeleteCustomer(long CustomerID)
        {
            Console.WriteLine(CustomerID);
            TempData["account"] = null;
            CustomerAccDeleteModel customerAccDeleteModel = new CustomerAccDeleteModel();
            customerAccDeleteModel.customer = _repo.getCustomerByCID(CustomerID);
            customerAccDeleteModel.accounts = _repo.GetAllAccountsByCustomerID(CustomerID);            
            if(customerAccDeleteModel.accounts.Count != 0)
            {
                TempData["account"] = "exist";
            }
            return View(customerAccDeleteModel);
        }

        [HttpPost]
        public IActionResult DeleteCustomer(Customer customer)
        {
            TempData["account"] = "Customer "+customer.CustomerID + " has been deleted";
            _repo.DeleteCustomer(customer);            
            return RedirectToAction("Index");
        }

        public IActionResult CreateAccount(long CustomerID)
        {
            List<Account> accounts = _repo.GetAllAccountsByCustomerID(CustomerID);
            //TempData["exist"] = null;
            if (accounts.Count == 2) 
            {
                TempData["exist"] = "User already has Checking and Savings account!";
                return View();
            } else if(accounts.Count == 1)
            {
                return View(accounts.First());
            }
            Account account = new Account();
            account.CustomerID = CustomerID;
            return View(account);
        }

        [HttpPost]
        public IActionResult CreateAccount(Account account)
        {
            TempData["account"] = null;
            TempData["accountCreated"] = null;

RetailBankManagementSystem/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title class="text-light">@ViewData["Title"] - Retail Banking Services</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </head>
    <body style="background-image: linear-gradient(180deg, lavender, white) ">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Retail Banking Services</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">

                            @if (User.IsInRole("Cashier"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-controller="Cashier" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-controller="Cashier" asp-action="Search">Search</a>
                                </li>
                            }

                            @if (User.IsInRole("CustomerExecutive"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Executive" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Executive" asp-action="Create">Add</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Executive" asp-action="SearchCustomer">Search</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Executive" asp-action="ViewAccountsIndex">Accounts</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted bg-dark text-light">
            <div class="container text-center">
                &copy; <b>2021 - RetailBank</b>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>